### ISSUE TITLE
Bungeecord/velocity

### ISSUE THREAD

**Issue by UltraHispeed-Elite** [ViaVersion/ViaProxy#103]
Is there a plug-in/method/alternative I could use to connect these servers to a bungeecord, waterfall, or velocity server?

**Comment by RaphiMC** [comment]
Please describe more precisely what you want. ViaProxy itself is a standalone application and works with any server (Bungeecord, Waterfall, Spigot, Forge, Fabric, Vanilla, even self written ones)

**Comment by UltraHispeed-Elite** [comment]
I tried that before and the via proxy kept sending an error message saying the client was unable to connect to the network with some error message involving version incompatibility

**Comment by RaphiMC** [comment]
Without any more information I won't be able to help you

**Comment by UltraHispeed-Elite** [comment]
Ok I won’t be able to test it out again until tonight I’ll try again and give you the results when I do

**Comment by UltraHispeed-Elite** [comment]
Thanks for helping out though

**Comment by UltraHispeed-Elite** [comment]
Hello me again I have a picture of what happens
![Uploading 271D5112-047A-4465-9DAA-58E9167E28E4.jpeg…]()

**Comment by UltraHispeed-Elite** [comment]
![16658720-246B-4E01-A6FB-F7577FD9FE60](https://github.com/ViaVersion/ViaProxy/assets/62296749/9f582e1d-e9be-4498-8f4f-3062212b1eb4)

**Comment by UltraHispeed-Elite** [comment]
nvm I fixed my issue

**Comment by FJKiXfaR** [comment]
> nvm I fixed my issue

how to fix it
