### ISSUE TITLE
Bedrock does not log in

### ISSUE THREAD

**Issue by Ferrarisrex** [ViaVersion/ViaProxy#104]
![image](https://github.com/ViaVersion/ViaProxy/assets/91031616/679a9db7-3287-4d6d-8631-e0f655f150f3)
this happens after trying to log in on bedrock

**Comment by RaphiMC** [comment]
Update ViaProxy to the latest dev version

**Comment by Ferrarisrex** [comment]
that didn't fix it, it just made it appear in game
![image](https://github.com/ViaVersion/ViaProxy/assets/91031616/73ade70f-185e-43ab-b12f-89e8b48f351a)
