### ISSUE TITLE
Suggestion - use config.yml instead of arguments

### ISSUE THREAD

**Issue by candrawardana** [ViaVersion/ViaProxy#173]
just like the title

**Comment by RaphiMC** [comment]
I definitely don't want to remove the CLI arguments, since they also have their use cases, but offering a config.yml which can be specified by a CLI argument would be a good idea (--config config.yml for example). Needs a whole config system refactor tho, so it won't happen quickly

**Comment by FlorianMichael** [comment]
Implemented with https://github.com/ViaVersion/ViaProxy/commit/0cb34ed553998c06238b08b15ffce0d589a9ba14, @RaphiMC needs to update the README file though.
