### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by rikoshet185** [ViaVersion/ViaProxy#176]
The Via Proxy stopped running after a certain period of time. Nothing happens when you try to start it. Everything is fine with other jar files. what files can I send to understand what happened to me?

**Comment by RaphiMC** [comment]
You can upload the log file of ViaProxy and try running the ViaProxy jar in a command line window (cmd on windows) to get additional output (Upload that as well here). Also describe the bug better, since I don't understand what your issue even is

**Comment by rikoshet185** [comment]
https://youtu.be/oGuKn5fSlT8 Video
[log.txt](https://github.com/ViaVersion/ViaProxy/files/14188113/log.txt)

**Comment by rikoshet185** [comment]
[log.txt](https://github.com/ViaVersion/ViaProxy/files/14188183/log.txt)

**Comment by RaphiMC** [comment]
Can you put ViaProxy into its own folder so it doesn't attempt to load plugins from your plugins folder on your desktop. Also upload the actual ViaProxy latest.log in the logs folder of ViaProxy (Do that after you put ViaProxy in a new folder) when you attempt to double click it

**Comment by rikoshet185** [comment]
[latest.log](https://github.com/ViaVersion/ViaProxy/files/14395466/latest.log)
Everything works fine in a separate folder

**Comment by RaphiMC** [comment]
Update ViaProxy to 3.2.0, try again and upload the log if it still doesn't start

**Comment by RaphiMC** [comment]
Closed due to inactivity

**Comment by Outfit8TSB** [comment]
this issue is already resolved and this issue was not confirmed to be a bug.
rikoshet185 did not press the start button in gui. 
rikoshet185 should Press Start Button to start ViaProxy.

**Comment by rikoshet185** [comment]
> this issue is already resolved and this issue was not confirmed to be a bug. rikoshet185 did not press the start button in gui. rikoshet185 should Press Start Button to start ViaProxy. Let me tell more about it:
> 
> ```
> [09:08:04] [Via Async Scheduler 0/INFO] (ViaVersion) Finished mapping loading, shutting down loader executor!
> ```
> 
> means the viaproxy is loaded and you must press a start button.

It wasn't about the start button. Now I can guess why this happened.
