### ISSUE TITLE
"block-versions" config causes viaproxy to break

### ISSUE THREAD

**Issue by Kichura** [ViaVersion/ViaProxy#179]
When modifying the viaversion to filter out minecraft versions, it causes viaproxy to stop loading viaversion correctly.

Error can be found [here](https://pastebin.com/raw/URad6N4y),
and ViaVersion config can be found [here](https://pastebin.com/raw/yCFhxgxZ).

**Comment by FlorianMichael** [comment]
Is this ViaVersion config file valid? Can you run it on Spigot?

**Comment by RaphiMC** [comment]
Happens on Bungeecord as well. Seems to be a general Via issue where the config is loaded before the Via platform is loaded (And when the config class tries to log something (for example an invalid version in the block-versions list) it crashes as Via isn't loaded yet)
