### ISSUE TITLE
Show ViaProxy's brand info in F3

### ISSUE THREAD

**Issue by Kichura** [ViaVersion/ViaProxy#181]
By default, ViaProxy does not reveal it's own branding info in F3 compared to VIAaaS when joining a third-party server - and since this can make certain server owners confused on how they joined the server using a older/newer vanilla client while the server itself has no viaversion plugin installed, ViaProxy should consider adding a feature to F3 that does just that.

A few examples i can make up:

A: `ViaProxy (3.1.0) <- vanilla`
B: `ViaProxy (C: 1.20.4 S: 1.20.1) <- vanilla`
C: `vanilla (ViaProxy)`
D: `vanilla (ViaProxy 3.1.0)`
E: `vanilla (ViaProxy C: 1.20.4 S: 1.20.1)`
F: `vanilla (ViaProxy (3.1.0) C: 1.20.4 S: 1.20.1)`

As for my personal preferences, i either assume that A or C work the best mostly due to aesthetic reasons.

**Comment by RaphiMC** [comment]
Probably gonna use `ViaProxy (clientversion) -> serverbrand (serverversion)` (Example: `ViaProxy (1.20.4) -> vanilla (1.20.1)`)

**Comment by RaphiMC** [comment]
Implemented in https://github.com/ViaVersion/ViaProxy/commit/15b4d4ec90310f56ffa6d5466e71693bdffd2d74
