### ISSUE TITLE
Suggestion - Custom MOTD 

### ISSUE THREAD

**Issue by Krafting** [ViaVersion/ViaProxy#188]
It would be cool to be able to edit the MOTD displayed by the proxy:

![image](https://github.com/ViaVersion/ViaProxy/assets/36538123/5527752f-c032-4058-b2e8-d2799e86d72f)

![image](https://github.com/ViaVersion/ViaProxy/assets/36538123/046d2142-9958-43cb-8d97-b0f11a2dbb3a)

Or maybe I'm missing something and this should be done in another way ?

My setup is:  ViaProxy -> b1.7.3 server

Thank you!

**Comment by RaphiMC** [comment]
Good idea, will be implemented after #173
