### ISSUE TITLE
Suggestion - Please add PacketFix to reduce the misblocking of high version servers.

### ISSUE THREAD

**Issue by keke1145** [ViaVersion/ViaProxy#209]
Hello, can PacketFix be added to VIAProxy to reduce the misblocking?

**Comment by RaphiMC** [comment]
What is PacketFix and what even is the issue?

**Comment by keke1145** [comment]
> 什么是 PacketFix，问题到底是什么？
Hello, when I was playing on the Chinese Hua Yu Ting server, because the version of that server is 1.12.2, it caused a wrongful block. So, can you add a packet fix to reduce the misblocking?

**Comment by keke1145** [comment]
Do you need me to take a screenshot for you to see?

**Comment by RaphiMC** [comment]
I don't understand what the issue is nor what you want. Please describe with more details and upload a log + screenshots

**Comment by RaphiMC** [comment]
Closed due to inactivity
