### ISSUE TITLE
Error with via version

### ISSUE THREAD

**Issue by tagelis** [ViaVersion/ViaProxy#228]
[message.txt](https://github.com/user-attachments/files/15803615/message.txt)

We have Pupperfish 1.20.2 and have enabled versions 1.8 and 1.16 to 1.20. We also have these plugins installed -> ViaBackwards-4.10.2 | ViaRewind-3.1.2 | ViaVersion-4.10.2

**Comment by RaphiMC** [comment]
This is not related to ViaProxy. Please open the issue on the correct issue tracker (https://github.com/ViaVersion/ViaBackwards)
