### ISSUE TITLE
ViaProxy incompatibility 3.3.1 with Bedrock Realms

### ISSUE THREAD

**Issue by FolioForThatGuy** [ViaVersion/ViaProxy#238]
Running latest release.
Same issue as #208, can't request to connect to a bedrock realm running java edition.
Tried previous version which shot the same error. 
![Version 3.3.1](https://github.com/user-attachments/assets/dea02136-5b8d-4535-8f2f-f99c4ee575d0)
![Version 3.3.0](https://github.com/user-attachments/assets/bb35cb4e-d0cb-4855-b582-6a36594e5e68)
Running Java 18.
Console doesn't shoot any errors either.

**Comment by FolioForThatGuy** [comment]
Also tried the latest devbuild version 3.3.2 [here](https://build.lenni0451.net/job/ViaProxy/), still no dice

**Comment by RaphiMC** [comment]
Fixed in latest dev build. Please redownload it

**Comment by FolioForThatGuy** [comment]
Thanks for that. On the latest dev build I am now able to join but cannot interact with the world or load new chunks. I can type, walk about and don't get kicked, but that's about it.
[Here's](https://mclo.gs/Zs0Ueky) the dump, I experienced an error loading realms at the start but didn't get it again after refreshing it.

**Comment by RaphiMC** [comment]
ViaBedrock is currently not very finished and not ready for normal gameplay. Here is a list of features that are working: https://github.com/RaphiMC/ViaBedrock?tab=readme-ov-file#features
