### ISSUE TITLE
collapse

### ISSUE THREAD

**Issue by fwwfdwd** [ViaVersion/ViaProxy#243]
I opened ViaProxy completely following the tutorial and encountered a cmd that crashed without outputting any information

**Comment by RaphiMC** [comment]
Please provide more details, like what command failed and what the output of that is. You could send a screenshot of the console window

**Comment by fwwfdwd** [comment]
Cmd closed without any output results. I infer it should be a problem with the Java version because I installed Java 8.0.411 on another computer and started the program normally. Please tell me which version of Java I prefer to use

**Comment by fwwfdwd** [comment]
Cmd closed without any output results. I infer it should be a problem with the Java version because I installed Java 8.0.411 on another computer and started the program normally. Please tell me which version of Java you are using

**Comment by RaphiMC** [comment]
I recommend to use Java 21. If you need any further help provide more details, because saying "I ran some command and it didn't do anything" isn't helpful

**Comment by fwwfdwd** [comment]
Thank you very much. I think there was a problem with my Windows 10 system configuration. After installing Java21, I successfully ran the software using the cd command in cmd
