### ISSUE TITLE
Game crashes while playing on 1.7.2 on a 1.21 server

### ISSUE THREAD

**Issue by NPC-Master3304** [ViaVersion/ViaProxy#254]
[viaversion dump](https://dump.viaversion.com/3bc799d84ee6e98a52bc4b426fb9813630910de4818be03906c8a6ee2b11d8a3)
[viaproxy log](https://mclo.gs/OA55FpE)
[client crash](https://mclo.gs/PXZGGFu)
btw I also downloaded the most recent snapshot, and the same thing still occurs. same thing with unticking everything in the advanced tab on viaproxy.
EDIT: seems to be 1.7.X since 1.8 and above is fine.

**Comment by FlorianMichael** [comment]
Please open a new issue following the issue template on this repository: https://github.com/ViaVersion/ViaRewind/issues
