### ISSUE TITLE
Unable to join 1.21.3 bedrock realms server

### ISSUE THREAD

**Issue by Kurt6** [ViaVersion/ViaProxy#255]
Cant join 1.21.3 bedrock realms

- When trying to join from 1.21 to a bedrock realm it just says unable to connect to backend server and doesnt allow you to join.

**Comment by RaphiMC** [comment]
Upload the ViaProxy log (Advanced tab -> Upload log) after you tried joining

**Comment by Kurt6** [comment]
https://mclo.gs/ENSnyVL

**Comment by RaphiMC** [comment]
Can you record a video of the issue and all the steps you do in ViaProxy before joining

**Comment by Kurt6** [comment]
> Can you record a video of the issue and all the steps you do in ViaProxy before joining


https://github.com/user-attachments/assets/f1f4d38e-c123-4a79-8f07-e999461a654f

**Comment by RaphiMC** [comment]
Try it with a vanilla client

**Comment by RaphiMC** [comment]
Do you have a non macos computer you can try this on?

**Comment by Kurt6** [comment]
> Do you have a non macos computer you can try this on?

Yes, let me make an attempt and I will get back to you, have to install mc + software.

**Comment by Kurt6** [comment]
> Do you have a non macos computer you can try this on?

I tried a fresh install of Windows on 1.21, and it connected and worked; I will try a fresh install of Java and the game on Mac and see if it solves the problem.

**Comment by Kurt6** [comment]
> > Do you have a non macos computer you can try this on?
> 
> I tried a fresh install of Windows on 1.21, and it connected and worked; I will try a fresh install of Java and the game on Mac and see if it solves the problem.


Fresh install of MacOS and minecraft and ViaProxy, getting the same error as before and not connecting to the backend server.

Here is the log file from the latest version with a fresh install: https://mclo.gs/ZpuHdEa

**Comment by RaphiMC** [comment]
Can you install [wireshark](https://www.wireshark.org/download.html) and let it record the packets ViaProxy sends (After starting wireshark, select your main network interface to start recording, then use ViaProxy and stop the packet recorder after you get disconnnected). After you are done go to the filter field of wireshark and filter for `raknet` (press enter to submit). Make a screenshot of the full window and send it (you can dm it on discord if you want: `rk_01`)

**Comment by Kurt6** [comment]
> Can you install [wireshark](https://www.wireshark.org/download.html) and let it record the packets ViaProxy sends (After starting wireshark, select your main network interface to start recording, then use ViaProxy and stop the packet recorder after you get disconnnected). After you are done go to the filter field of wireshark and filter for `raknet` (press enter to submit). Make a screenshot of the full window and send it (you can dm it on discord if you want: `rk_01`)

Added you on discord

**Comment by RaphiMC** [comment]
> try 74.235.56.167_30222_Bedrock-1.21.2.viaproxy.localho.st which is public wildcard hostname, to enable public wildcard hostname for bedrock and java: enable forward-hostname in geyser config set wildcard-domain-handler to Public in ViaProxy restart viaproxy.
> 
> select the account and then join with 74.235.56.167_30222_Bedrock-1.21.2.viaproxy.localho.st

This is unrelated to the issue. Public wildcard hostname doesnt even support Realms.

**Comment by RaphiMC** [comment]
Closing because I already fixed the issue in the latest dev build
