### ISSUE TITLE
Cannot generate config and upload

### ISSUE THREAD

**Issue by aryanmcr** [ViaVersion/ViaProxy#256]
On my ultraservers minecraft server, I am using geyser, viafabric, viarewind and viabackwards to play on a fabric 1.20.6 server, however when my updated bedrock players join it says outdated proxy. it also asks me to update but when i do it says its for 1.21 and crashes. i tried running it on my pc then uploading the files to ultraservers but it didnt work. i cant run commands to start it online

**Comment by RaphiMC** [comment]
Try using the latest dev build: https://ci.viaversion.com/view/Platforms/job/ViaProxy/
If its still broken upload the log file

**Comment by aryanmcr** [comment]
So i upload this to my mods folder? with geyser and via*

**Comment by RaphiMC** [comment]
ViaProxy is not a mod. Read the instructions or join the ViaVersion discord server for support
