### ISSUE TITLE
Joining 1.20.6 server on 1.7.10 causes problem with server resource pack

### ISSUE THREAD

**Issue by sj-dan** [ViaVersion/ViaProxy#257]
Upon joining the server, I get "Making request... 0%", and it gets stuck that way.
![image](https://github.com/user-attachments/assets/8183afc2-7d96-499d-b717-c57535406068)

Upon inspection of my game's console, the following error shows up:

`[18:06:23] [File Downloader #2/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.net.MalformedURLException: no protocol: �https://mytexturepack.url/pack.zip`

**Comment by RaphiMC** [comment]
Resource packs are not supported/translated by ViaVersion. Decline the resource pack to join the server

**Comment by sj-dan** [comment]
The issue isn't the resource pack itself, but rather the malformed packet being sent. there seems to be 2 additional characters infront of the https that's throwing off the client. I assume they're part of the packet itself and shouldnt show up in the URL?

**Comment by RaphiMC** [comment]
Yes thats true, that would probably be a ViaRewind issue if you want to report it there, but even if that issue is fixed the resource pack won't work because its not made for 1.7.10 and Via* isn't translating it
