### ISSUE TITLE
unable to connect on version 1.6.4 and under and allow legacy client passthrough is set to true

### ISSUE THREAD

**Issue by MrLenDev** [ViaVersion/ViaProxy#262]
allow legacy client passthrough set on true and still can't connect on version 1.6.4 and under

https://github.com/user-attachments/assets/dce2b242-86b7-47ff-ba7c-ade5131acef3

**Comment by FlorianMichael** [comment]
As the description of the setting says, no protocol translation is being applied. Legacy client passthrough only allows clients with the same version as the server to join to prevent having different ports for ViaProxy and normal users. ViaProxy only allows versions 1.7+ to join.

**Comment by MrLenDev** [comment]
are you sure? show me footage.

**Comment by FlorianMichael** [comment]
You just have to read the README.md file or the description of the setting in the config file

**Comment by MrLenDev** [comment]
oh now i get it! this issue is closed

**Comment by MrLenDev** [comment]
i kinda wish there was a plugin for viaproxy that allowed you to connect 1.6.4 and alphas and betas
