### ISSUE TITLE
Usage for Server owners (Online Mode Server)

### ISSUE THREAD

**Issue by Silverteal** [ViaVersion/ViaProxy#280]
Since viaproxy.yml requires user to configure online mode account in GUI, does it mean that it's impossible to use ViaProxy on online server (server-side) ? I wanted to use geyser.

**Comment by RaphiMC** [comment]
Yes its impossible to use ViaProxy on online mode servers without adding an account in the GUI. Minecraft Proxies (Bungeecord, Velocity, ViaProxy) can't tunnel online mode sessions. If you specifically want to use Geyser, you can install floodgate on the backend server and copy the key to the ViaProxy Geyser installation (Instructions are on Geyser's website)
