### ISSUE TITLE
omg I can't run viaproxy

### ISSUE THREAD

**Issue by cxk666nb** [ViaVersion/ViaProxy#283]
I installed java8 and java17, but it didn't work

**Comment by Earthcomputer** [comment]
omg

**Comment by Lenni0451** [comment]
> I installed java8 and java17, but it didn't work

It would be really helpful if you could provide more information that just `y it no work :(`

**Comment by RaphiMC** [comment]
Please read the instructions in the README (https://github.com/ViaVersion/ViaProxy?tab=readme-ov-file#usage-for-players-gui)
