### ISSUE TITLE
moving bug

### ISSUE THREAD

**Issue by szemuveges** [ViaVersion/ViaProxy#301]
when im using 1.16.5 with viaproxy on 1.18.2 it has like a moving bug like the anticheat is thinking that i am cheating so it just kicks me out of the server and it says you are cheating

**Comment by RaphiMC** [comment]
ViaProxy has warned you before using it that there might be issues with strict anticheats. Mojang often changes small things in the movement code which can cause those issues and its not fixable without modding the game
