### ISSUE TITLE
Can't Connect to My Accounts

### ISSUE THREAD

**Issue by FireKing2006** [ViaVersion/ViaProxy#307]
I tried to connect to my bedrock account and thats what pops up to me, and also I tried to connect to my microsoft account and the same popped up, what should I do??
![Screenshot 2024-10-16 100426](https://github.com/user-attachments/assets/5ed64cc4-1e13-43e3-a59b-6ceb3621832e)
![Screenshot 2024-10-16 100440](https://github.com/user-attachments/assets/99b00fb4-e262-46f8-bbef-df8a2f39ebd7)

**Comment by RaphiMC** [comment]
Something is wrong with your computer certifcates or Microsoft servers have temporary issues. Try again in a few hours. If that doesn't work try it on a different network. If its still not working reinstall Java (Use Java 17 or newer)

**Comment by FireKing2006** [comment]
ok thx I updated Java and now I could add the account but I cant join to my bedrock server at all, the server is online but I cant Join it.
![image](https://github.com/user-attachments/assets/7f176d8f-6f75-49fd-b2d1-19eb9d4e7c82)
![image](https://github.com/user-attachments/assets/5c4012d0-2719-49ad-b58f-f35a6cf3336c)

**Comment by RaphiMC** [comment]
Upload a screenshot of the General and Accounts tabs

**Comment by FireKing2006** [comment]
![image](https://github.com/user-attachments/assets/58ecd6d4-7d78-4359-9192-27ee23b9a31c)
![image](https://github.com/user-attachments/assets/0cf3d873-29e5-4cbf-98af-832149c3abe4)

**Comment by RaphiMC** [comment]
Seems correct. Upload the ViaProxy log (Advanced tab -> Upload log)

**Comment by RaphiMC** [comment]
Looks like you aren't using a valid account on your Minecraft Java Edition client. Either disable proxy online mode in the Advanced tab or launch the game with a valid account

**Comment by FireKing2006** [comment]
I disabled the proxy online as I dont have a valid account for Minecraft Java Edition client, however this is now shoing
![image](https://github.com/user-attachments/assets/8d10165f-e5c6-4c4a-baa3-1751be9c0bb0)

**Comment by RaphiMC** [comment]
Upload the log again

**Comment by FireKing2006** [comment]
https://mclo.gs/4wfyZoZ

**Comment by RaphiMC** [comment]
This log does not contain any connection attempts

**Comment by FireKing2006** [comment]
nvm now I joined perfectly thx, however when I joined the server and when I break blocks, nothing drops to pickup and I can't drop items to other players

**Comment by AlexProgrammerDE** [comment]
There are many game features missing in Bedrock Edition that RK_01 is still working on. Here is a fully list of what works and what doesn't: https://github.com/RaphiMC/ViaBedrock#features

**Comment by FireKing2006** [comment]
oh ok thx alot
