### ISSUE TITLE
Parts of or the entire map not rendering on a minecraft classic server

### ISSUE THREAD

**Issue by FloppyMacguffum** [ViaVersion/ViaProxy#313]
When I connect with ViaProxy (target runs latest vanilla classic server software downloaded from [betacraft.uk](https://files.betacraft.uk/server-archive/classic/c1.10.1.zip)) on MC 1.21.3, parts of or the entire map will not render. The map has loaded, but block textures will not show up. I know this because I can still interact with the terrain around me. I don't know if this is specifically an issue with ViaProxy or ViaLegacy but I had to put the issue somewhere.
![2024-10-28_10 49 45](https://github.com/user-attachments/assets/36d3ed63-b37d-4241-874b-26041b00afa9)
![2024-10-28_10 49 40](https://github.com/user-attachments/assets/da319c4b-d5bd-4cdd-9a11-6bfb972f0b18)
![2024-10-28_10 49 34](https://github.com/user-attachments/assets/85ae677d-a98f-439c-a323-94a48edbbb03)

**Comment by RaphiMC** [comment]
Can you check if it works with 1.21.1?

**Comment by RaphiMC** [comment]
Managed to reproduce it on a 1.8 server with a 1.21.3 client. This means that its a ViaVersion issue. I will leave this issue open here

**Comment by RaphiMC** [comment]
This has been fixed in the latest dev builds of ViaProxy: https://ci.viaversion.com/view/Platforms/job/ViaProxy/
