### ISSUE TITLE
error on bedrock server

### ISSUE THREAD

**Issue by PurpleProg** [ViaVersion/ViaProxy#316]
Client:
minecraft java 1.21.1

Server:
minecrat bedrock 1.21.40.03

Error:
"Please log in into Xbox to join this server (reason: Unknown)"

ViaProxy:
v3.3.4

I'm pretty sure i am logged in as i can connect to other (java) servers.

**Comment by RaphiMC** [comment]
This means that you have to add your bedrock account in ViaProxy and to make sure to have it selected

**Comment by PurpleProg** [comment]
Oh yeah I've used a java account... And i just read that issues with ViaBedrock shall not be reported yet, sorry and thanks for that immediate reply.
