### ISSUE TITLE
Unable to connect to any server

### ISSUE THREAD

**Issue by MineKat** [ViaVersion/ViaProxy#320]
I get this error every time I try to connect to any Bedrock 1.21 server.
![image](https://github.com/user-attachments/assets/d2d8199e-8cb1-449f-b416-78208d985b29)

Connection Lost
Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet play/clientbound/minecraft:add_experience_orb <ClientboundAddExperienceOrbPacket) was
larger than I expected, found 126 bytes extra whilst reading packet clientbound/minecraft:add_experience_orb

Ive attempted to join on 1.8.9 optifine, 1.21.3 optifine + fabric, and 1.20 Vanilla and they all give me the same error. I had resource packs enabled and disabled on various server joining attempts.

**Comment by RaphiMC** [comment]
Already fixed. Update to the dev build of ViaProxy: https://ci.viaversion.com/view/Platforms/job/ViaProxy/
