### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Veslydev** [ViaVersion/ViaProxy#326]
can it be like viafabricplus for not flagging ac etc like when viafabric was firstly released it was bad but on viafabricplus it was so good can't it be like that?

**Comment by RaphiMC** [comment]
ViaProxy can't change clientside code to fix movement differences or other game mechanics. Even with clientside code its really hard. Thats why ViaFabricPlus is only available for the latest game version, while ViaFabric and ViaProxy support far more client versions
