### ISSUE TITLE
where is the code to connect your microsoft account to viaproxy

### ISSUE THREAD

**Issue by Words-Words** [ViaVersion/ViaProxy#339]
whenever i click microsoft account on the viaproxy gui it just takes me to a microsoft page saying "enter code to allow acess" but i dont see a code anywhere

**Comment by RaphiMC** [comment]
The code should be automatically filled in. If its not you can find the code here:
![image](https://github.com/user-attachments/assets/94b111c4-c047-40a6-a4d2-66dfdd43455a)
