### ISSUE TITLE
Cannot run with less than 256mb RAM

### ISSUE THREAD

**Issue by srzmnx** [ViaVersion/ViaProxy#61]
I have over 8000mb worth of ram, but whenever I try to run viaproxy it just gives me a 
![image](https://github.com/ViaVersion/ViaProxy/assets/83734653/5f0e83cb-2f78-49b8-a290-80ac0f8e5bff)

**Comment by RaphiMC** [comment]
You should install 64-Bit java and try it with that

**Comment by srzmnx** [comment]
it worked, thank you so much!
