### ISSUE TITLE
An error occured while connecting to the backend server: null

### ISSUE THREAD

**Issue by srzmnx** [ViaVersion/ViaProxy#62]
I'm trying to connect to a websocket 1.5.2 anarchy server (eagler) using 1.8 with Via, but it slaps me with a strange error message. "An error occured while connecting to the backend server: null" I've seen other connect to the same server. It is an offline server, and no account is specified. The ip to the websocket server is "wss://mc.gmod9.com/wssconnect" if possible, could anyone set it up for me please? you dont have to, but it would really be a help. I'm using a 25565 port, by the way.

**Comment by RaphiMC** [comment]
Connecting to eagler craft servers is not supported
