### ISSUE TITLE
登入微软账号出现问题

### ISSUE THREAD

**Issue by szzz666** [ViaVersion/ViaProxy#66]
![image](https://github.com/ViaVersion/ViaProxy/assets/60167194/9d633756-4bd6-4a84-a41f-c1b8c2cc9b55)

**Comment by RaphiMC** [comment]
Send the log file (latest.log) of the session where the error occurred. Also does it happen everytime or was that only once? Maybe you should try it again later because the error code hints at a fault with microsoft servers

**Comment by szzz666** [comment]
每次都错误

**Comment by szzz666** [comment]
对了能不能支持进入nukkit服务器

**Comment by szzz666** [comment]
[latest.log](https://github.com/ViaVersion/ViaProxy/files/11738298/latest.log)
[debug.log](https://github.com/ViaVersion/ViaProxy/files/11738299/debug.log)

**Comment by RaphiMC** [comment]
I assume the error is fixed (Most likely temporary microsoft server issue) because in your other issue the log shows a sucessful login in your microsoft account. Can you confirm that the error is fixed?

**Comment by szzz666** [comment]
后面可以登录了之前不知道怎么回事，你看看为什么不能进入nukkit服务器吧

**Comment by RaphiMC** [comment]
The Nukkit issue is tracked in the other issue you opened and not here
