### ISSUE TITLE
无法进入nukkit核心开的基岩版服务器

### ISSUE THREAD

**Issue by szzz666** [ViaVersion/ViaProxy#67]
![image](https://github.com/ViaVersion/ViaProxy/assets/60167194/1d1aa6a6-c984-402e-80e8-af080449f52b)

**Comment by RaphiMC** [comment]
Please provide more details in the error report such as logs

**Comment by szzz666** [comment]
![QQ截图20230614034557](https://github.com/ViaVersion/ViaProxy/assets/60167194/c40c414c-a9ec-45f9-a580-2bfc335faf7a)

**Comment by RaphiMC** [comment]
I need the log file of ViaProxy and not a screenshot of the error

**Comment by szzz666** [comment]
[latest.log](https://github.com/ViaVersion/ViaProxy/files/11738706/latest.log)
[debug.log](https://github.com/ViaVersion/ViaProxy/files/11738708/debug.log)

**Comment by szzz666** [comment]
希望可以适配https://github.com/PowerNukkitX/PowerNukkitX和https://github.com/MemoriesOfTime/NukkitPetteriM1Edition核心开的基岩版服务器

**Comment by RaphiMC** [comment]
I will look at the issue when I have time, thanks for the details

**Comment by szzz666** [comment]
如果成功了，请通知我，谢谢

**Comment by szzz666** [comment]
如果基岩版服务器，可以让Java版客户端进，并且可以正常游玩，那是非常好的

**Comment by RaphiMC** [comment]
I don't understand your last comment (Through translation with deepl.com), but I will fix the issue when I have time

**Comment by RaphiMC** [comment]
Fixed

**Comment by szzz666** [comment]
?

**Comment by szzz666** [comment]
看样子还没有修复
无法进入nukkit核心开的基岩版服务器
![image](https://github.com/ViaVersion/ViaProxy/assets/60167194/8f49ff82-aa8d-4ce0-8991-1eb9
[debug.log](https://github.com/ViaVersion/ViaProxy/files/11854293/debug.log)
20c6eb27)

[latest.log](https://github.com/ViaVersion/ViaProxy/files/11854294/latest.log)

**Comment by RaphiMC** [comment]
I just tested: Nukkit, PowerNukkit, BDS and PMMP and all of them worked. You have to update ViaProxy like its described in the readme of ViaBedrock (Download the latest dev build)

**Comment by szzz666** [comment]
有没有测试过Nukkit mot

**Comment by RaphiMC** [comment]
As I said, I just tested all popular bedrock server software (list above). Please just update ViaProxy with the instructions found in the ViaBedrock readme

**Comment by szzz666** [comment]
ok

**Comment by szzz666** [comment]
能进服务器但是不能交互，背包物品也无法加载

**Comment by RaphiMC** [comment]
Yes, you can't interact with items because thats not implemented. For a list of features see the ViaBedrock readme
