### ISSUE TITLE
An unhandled error occurred in your connection and it has been closed

### ISSUE THREAD

**Issue by sj-dan** [ViaVersion/ViaProxy#73]
![image](https://github.com/ViaVersion/ViaProxy/assets/48661313/b11e82e4-a64d-4af5-a4f2-059e23fb7241)
Hope this helps. Was joining a 1.20 server using 1.8.8

**Comment by RaphiMC** [comment]
Please test this using the [latest dev build of ViaProxy](https://ci.viaversion.com/view/All/job/ViaProxy/lastSuccessfulBuild/artifact/build/libs/ViaProxy-3.0.20-SNAPSHOT.jar).
If its still broken press the "Upload logs" button in the advanced tab as well as the "Create ViaVersion dump" and include both links

**Comment by RaphiMC** [comment]
Closed due to inactivity
