### ISSUE TITLE
Microsoft login 403 error

### ISSUE THREAD

**Issue by a-a3458** [ViaVersion/ViaProxy#77]
![Screenshot 2023-07-16 205451](https://github.com/ViaVersion/ViaProxy/assets/64805690/a93bccb3-75fc-4fc1-b3e5-0c4229758fd9)

**Comment by RaphiMC** [comment]
That error is already known, I don't know how to replicate it tho

**Comment by borjita2019** [comment]
> That error is already known, I don't know how to replicate it tho

couldn't it be the firewall or something blocking viaproxy itself

**Comment by RaphiMC** [comment]
It could be a lot of things, but it works in the most cases and I never had such an error myself thats why I can't really fix it

**Comment by RaphiMC** [comment]
Can you check if this error is fixed in the latest dev build of ViaProxy. If not please press the upload log button in the advanced tab and post the link here

**Comment by borjita2019** [comment]
> Can you check if this error is fixed in the latest dev build of ViaProxy. If not please press the upload log button in the advanced tab and post the link here

this was 4 months ago.. 😭

**Comment by DEMnetwork** [comment]
HTTP Error 403 Stands For
Forbidden
