### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Volcan4436** [ViaVersion/ViaProxy#79]
here are some Suggestions that would be nice to see:

- Auto Detect Server Version and dynamically Change the ViaProxy Config
- Add Support to run a Server Through ViaProxy and have it basically act like the server's ViaVersion
- Support for Browser Cookie Login, EasyMC Login and TheAlterning Login
- MCPatcher / TexturePack Generator to show newer Textures on older clients
- Ability to Save Servers to a List
- Client Brand Selector

Thx for taking the time to look at my suggestions

**Comment by Not-a-Tyler** [comment]
Would be nice to have it automatically try to find a saved premium account with the name the player joined with. I find it annoying to constantly have to switch accounts in its GUI to have multiple accounts connected.

**Comment by RaphiMC** [comment]
> Would be nice to have it automatically try to find a saved premium account with the name the player joined the proxy with. I find it annoying to constantly have to switch accounts in its GUI to have multiple accounts connected.

Good idea, can you please open a seperate issue
