### ISSUE TITLE
GUI duplicates itself when hovering over it

### ISSUE THREAD

**Issue by LostLuma** [ViaVersion/ViaProxy#85]
Hello. When using the GUI I ran into a problem of it duplicating itself multiple times whenever I hover with the cursor, which makes it rather unusable. This can happen two or three times on any of the screens, here's a [screenshot](https://files.lostluma.net/ilBEW3.png) of it in action.

Running this with Java 8, 17, and 20 all leads to the same issue.
I'm currently on Windows 11 with AMD driver version 23.7.1, if that is useful.

**Comment by RaphiMC** [comment]
Wow, interesting issue. Not sure what I can do to fix it because it never happened to me or was reported by someone else

**Comment by LostLuma** [comment]
Yeah I kind of thought that'd be the case, but still thought it might be useful to report just in case.

**Comment by LostLuma** [comment]
It seems that updating to a newly released GPU driver version has resolved this, sorry for the bother! 🦫
